### ISSUE TITLE
Add Voice Speed Control feature

### ISSUE THREAD

**Issue by ArchismanKarmakar** [SietseT/ElundusCoreApp#33]
**Is your feature request related to a problem? Please describe.**
This feature is going to control the speed of the speech generated.

**Describe alternatives you've considered**
Natural Reader is a good alternative but it is paid. There also a website called ttstool.com

**Comment by SietseT** [comment]
Unfortunately, I can't add this feature for two reasons:
1. The tool currently uses the StreamLabs API. As far as I know, it's not possible to change the voice speed using the API. Using ttstool.com is not a good alternative, since it has **global** rate-limits. Meaning, after a certain amount of requests, **no-one** will be able to convert text-to-speech until the cooldown period has elapsed. StreamLabs enforces rate-limits on a **per-client** basis, meaning that if I hit the rate-limit, you can still use it just fine.
2. I don't want to invest money into this, so Natural Reader or the official Amazon Polly API is not an option.
