### ISSUE TITLE
[BUG] API Error

### ISSUE THREAD

**Issue by yagalt** [SietseT/ElundusCoreApp#43]
**Describe the bug**
API no longer working?

**To Reproduce**
1. Go to Elundus Core
2. Select a voice
3. Click submit

**Expected behavior**
Expected an audio file to be generated

**Screenshots**
![image](https://github.com/SietseT/ElundusCoreApp/assets/45718137/928b5988-ffcd-4fb5-80d3-5bc2b079e037)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Could maybe be fixed by using StreamElements instead of Streamlabs?

**Comment by NoahDevelops** [comment]
Same issue on running on Mac

**Comment by theridon** [comment]
THE ELUNDUS CORE HAS BROKEN NOOOOOOOOO

**Comment by SlyCooperReloadCoded** [comment]
It's OS-independent then.

**Comment by SietseT** [comment]
The issue has been fixed in version 0.7.0 which I just released. It should be automatically updated for everyone who installed it.

The issue here was that StreamLabs (the API that is used to convert the TTS request) started enforcing CloudFlare protection on their API. I switched to StreamElements and all is working again!
