### ISSUE TITLE
About Mac

### ISSUE THREAD

**Issue by EfeFx** [SietseT/ElundusCoreApp#6]
Before it turned into an app, I could launch Elunduscore on my Mac via Chrome. But now apparently the website version of elunduscore has been removed. And MacOS can't run exe type files. So I can't reach it anymore by downloading it, nor launching it via Chrome. Perhaps you can bring back the website or create a MacOS (dmg) version for its app? Thank you for now.

**Comment by SietseT** [comment]
Thanks for your feedback.

Unfortunately it wasn't possible for me to keep hosting the website due to the fact that the API, that gets called whenever you want to convert a TTS message), has rate-limits in the setup that is required for a website. I had a workaround for the rate-limits by hosting more and more proxy API's, but as the website became more popular this was becoming an issue for me.

Now that the website is converted into an app, the rate-limit is no issue anymore, since the app comes bundled with a server that can call the required API's on it's own, without proxy API's.

Regarding MacOS, I'd love to create an installer for MacOS, but I don't have a Mac myself. I could create an installer, but I have no way to test the installer or the app itself. This is why I'm reluctant to distribute a MacOS version.

**Comment by prestonmcpeak** [comment]
+1 MacOS app would be nice. I understand your limitations though 🥲

**Comment by EfeFx** [comment]
The L_? shall never be forgotten xqcHands

**Comment by SietseT** [comment]
@EfeFx @prestonmcpeak MacOS support has been added in v0.5.0 which you can download from now on! Apparently, no changes had to be made for the app to run under MacOS, so that's great.
